t=(i for i in range(1,101) if i%2==0 if i%3==0)
# print(tuple(t))
# print(type(t))
# g=generator.BytesGenerator(5)
# print((g))
print((next(t)))
print((next(t)))
print((next(t)))
print((next(t)))
print((next(t)))
print((next(t)))
print((next(t)))
print((next(t)))
print((next(t)))
print((next(t)))
print((next(t)))
print((next(t)))
print((next(t)))
print((next(t)))
print((next(t)))
print((next(t)))
print((next(t)))